In [1]:
import pandas as pd
import numpy as np

In [2]:
# Creating Series
x = np.array([1,2,3,4,5])
y = pd.Series(x)
y

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [3]:
# Displaying datatype
y.dtype

dtype('int32')

In [4]:
# size allocated by the Series
y.size

5

In [5]:
#number of bytes consumed by the Series
y.nbytes

20

In [6]:
# Shape of the Series
y.shape

(5,)

In [7]:
# Displaying the nmuber of Dimensions
y.ndim

1

In [8]:
# length of the Series
len(y)

5

In [9]:
# Creating a Series from List
z = pd.Series([1,2,3] , index = ['x','y','z'])
z

x    1
y    2
z    3
dtype: int64

In [10]:
y

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [11]:
# Modifying Index in the Series
a = np.array(['a','b','c','d','e'])
y.index = a
y

a    1
b    2
c    3
d    4
e    5
dtype: int32

In [12]:
# Creating a series from Random Function and Arange Function
V2 = np.random.random(10)
ind = np.arange(0 , 10)
s = pd.Series(V2 , ind)
V2

array([0.4549703 , 0.77336842, 0.46013888, 0.11003433, 0.64218919,
       0.29129887, 0.82096212, 0.19069781, 0.35603118, 0.39500191])

In [13]:
V2 , ind

(array([0.4549703 , 0.77336842, 0.46013888, 0.11003433, 0.64218919,
        0.29129887, 0.82096212, 0.19069781, 0.35603118, 0.39500191]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [14]:
# Creatng a series from  a Dictionary
V1 = pd.Series({'a':1 , 'b':2 , 'c':3 , 'd':4 , 'e':5})
V1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [15]:
m = np.array(['aa','bb','cc','dd','ee'])
V1.index = m
V1

aa    1
bb    2
cc    3
dd    4
ee    5
dtype: int64

In [16]:
# Creating a series of a same number with different indexes
x = pd.Series(99 , index  = [1,2,3,4,5])
x

1    99
2    99
3    99
4    99
5    99
dtype: int64

In [17]:
#1 Different Things on Series with Pandas

In [18]:
# Slicing Series
s

0    0.454970
1    0.773368
2    0.460139
3    0.110034
4    0.642189
5    0.291299
6    0.820962
7    0.190698
8    0.356031
9    0.395002
dtype: float64

In [19]:
# return all elements of the Series
s[:]

0    0.454970
1    0.773368
2    0.460139
3    0.110034
4    0.642189
5    0.291299
6    0.820962
7    0.190698
8    0.356031
9    0.395002
dtype: float64

In [20]:
# first 3 elements
# last element
# Fecth first 4 elements
# Return all except last 2
# Return all except last

In [21]:
print( 'first three', s[:3])

first three 0    0.454970
1    0.773368
2    0.460139
dtype: float64


In [22]:
print('last element' , s[-1:])

last element 9    0.395002
dtype: float64


In [23]:
print('first four element' , s[:3])

first four element 0    0.454970
1    0.773368
2    0.460139
dtype: float64


In [24]:
print('Return all except last 2' , s[:-2])

Return all except last 2 0    0.454970
1    0.773368
2    0.460139
3    0.110034
4    0.642189
5    0.291299
6    0.820962
7    0.190698
dtype: float64


In [25]:
print('Return all except last ' , s[:-1])

Return all except last  0    0.454970
1    0.773368
2    0.460139
3    0.110034
4    0.642189
5    0.291299
6    0.820962
7    0.190698
8    0.356031
dtype: float64


In [26]:
# Return last 2 elements of the Series
print(s[-2:])
print(s[-1:-3])
# return last element  of the Series
s[-1:]

8    0.356031
9    0.395002
dtype: float64
Series([], dtype: float64)


9    0.395002
dtype: float64

In [27]:
#1.2 Append Series

In [28]:
s1 = pd.Series(np.arange(1,8) , index = ['a','b','c','d','e','f','g'])
s1

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [29]:
V1

aa    1
bb    2
cc    3
dd    4
ee    5
dtype: int64

In [30]:
s2 = s1.copy()
s2

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [31]:
V1

aa    1
bb    2
cc    3
dd    4
ee    5
dtype: int64

In [32]:
s4 = s2.append(V1)
s4

C:\Users\Shree123\AppData\Local\Temp\ipykernel_32228\3138531456.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  s4 = s2.append(V1)


a     1
b     2
c     3
d     4
e     5
f     6
g     7
aa    1
bb    2
cc    3
dd    4
ee    5
dtype: int64

In [33]:
s4.drop('g' , inplace = False)

a     1
b     2
c     3
d     4
e     5
f     6
aa    1
bb    2
cc    3
dd    4
ee    5
dtype: int64

In [34]:
s4

a     1
b     2
c     3
d     4
e     5
f     6
g     7
aa    1
bb    2
cc    3
dd    4
ee    5
dtype: int64

In [35]:
s4.drop('g' , inplace = True)
s4

a     1
b     2
c     3
d     4
e     5
f     6
aa    1
bb    2
cc    3
dd    4
ee    5
dtype: int64

In [36]:
#1.3 Operation on Series

In [37]:
V1  = np.array([10,20,30])
V2 = np.array([1,2,3])
s1 = pd.Series(V1)
s2 = pd.Series(V2)
s1,s2

(0    10
 1    20
 2    30
 dtype: int32,
 0    1
 1    2
 2    3
 dtype: int32)

In [38]:
# Adding 2 series
s1.add(s2)

0    11
1    22
2    33
dtype: int32

In [39]:
s2.add(s1)

0    11
1    22
2    33
dtype: int32

In [40]:
# Subtracting 2 series
s1.sub(s2)

0     9
1    18
2    27
dtype: int32

In [41]:
s2.sub(s1)

0    -9
1   -18
2   -27
dtype: int32

In [42]:
# Increment values in an individual series
s1.add(8)

0    18
1    28
2    38
dtype: int32

In [43]:
s1.sub(8)

0     2
1    12
2    22
dtype: int32

In [44]:
# multiply and divide each series 
print(s1.multiply(s2))
print(s1.divide(s2))

0    10
1    40
2    90
dtype: int32
0    10.0
1    10.0
2    10.0
dtype: float64


In [45]:
# Mulitply individual series by 1000
s1.multiply(1000)

0    10000
1    20000
2    30000
dtype: int32

In [46]:
print(s1.max())
print(s1.min())

30
10


In [47]:
s4 = s1

In [48]:
s1.equals(s4)

True

In [49]:
s5 = pd.Series([1,1,2,2,3,3] , index = [0,1,2,3,4,5])
s5

0    1
1    1
2    2
3    2
4    3
5    3
dtype: int64

In [50]:
# afind frequency
s5.value_counts()

1    2
2    2
3    2
dtype: int64

In [51]:
# 2 DataFrame

In [52]:
# 2.1 Create DataFrame

In [53]:
lang = ['Java' , 'Python' , 'Sql' , 'C++']
x = pd.DataFrame(lang)
x

0
0    Java
1  Python
2     Sql
3     C++

In [54]:
# Adding a column in a dataframe

In [55]:
rating = [1,2,3,4]
x[1] = rating
x

0  1
0    Java  1
1  Python  2
2     Sql  3
3     C++  4

In [56]:
# Renaming Columns
x.columns = ['Language' , 'Rating']

In [57]:
x

Language  Rating
0     Java       1
1   Python       2
2      Sql       3
3      C++       4

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Creating a dataframe from a dictionary 

In [26]:
data = [{'a':1, 'b':2}, {'a':5, 'b':10, 'c':20}]
df2 = pd.DataFrame(data)
df3 = pd.DataFrame(data, index=['row1', 'row2'], columns = ['a','b'])
df4 = pd.DataFrame(data, index=['row1', 'row2'], columns = ['a','b','c'])
df5 = pd.DataFrame(data, index=['row1', 'row2'], columns = ['a','b','c','d'])

In [27]:
df2

a   b     c
0  1   2   NaN
1  5  10  20.0

In [24]:
df3

a   b
row1  1   2
row2  5  10

In [25]:
df4

a   b     c
row1  1   2   NaN
row2  5  10  20.0

In [17]:
data2 =  pd.DataFrame(data)
data2

Name               Age  \
0  [x, y, z, abc]  [12, 32, 45, 62]   
1             NaN               NaN   

                                              Add  
0                                             NaN  
1  [wallstreet, pearson, silkson, silicon valley]

In [39]:
data3 ={'Name' : ['x','y','z','abc'],
                    'Age': [12,32,45,62] ,'Add': ['wallstreet','pearson','silkson','silicon valley']}

In [40]:
data4 = pd.DataFrame(data3)
data4

Name  Age             Add
0    x   12      wallstreet
1    y   32         pearson
2    z   45         silkson
3  abc   62  silicon valley

In [37]:
arr_ind = np.array(['a','b','c','d'])

In [41]:
data5 = pd.DataFrame(data3 , index = arr_ind)
data5

Name  Age             Add
a    x   12      wallstreet
b    y   32         pearson
c    z   45         silkson
d  abc   62  silicon valley

In [42]:
data6 = pd.DataFrame(data3 , index = ['ab','bc','cd','df'])
data6

Name  Age             Add
ab    x   12      wallstreet
bc    y   32         pearson
cd    z   45         silkson
df  abc   62  silicon valley

In [43]:
# Create a dataframe from a series of dictionary

In [46]:
dict = {'A': pd.Series([1,2,3,] , index = ['a','b','c']) ,
       'B': pd.Series([1,3,2,4] , index = ['a','b','c','d'])}
data = pd.DataFrame(dict)
data

A  B
a  1.0  1
b  2.0  3
c  3.0  2
d  NaN  4

In [47]:
# 2.2 Dataframe of Random Numbers with Date Indices

In [48]:
# use pandas date_range function

In [50]:
date1 = pd.date_range(start = '2022-12-18' , end = '2022-12-25')
date1

DatetimeIndex(['2022-12-18', '2022-12-19', '2022-12-20', '2022-12-21',
               '2022-12-22', '2022-12-23', '2022-12-24', '2022-12-25'],
              dtype='datetime64[ns]', freq='D')

In [55]:
data = pd.DataFrame(date1)
data.columns = ['Date']
data

Date
0 2022-12-18
1 2022-12-19
2 2022-12-20
3 2022-12-21
4 2022-12-22
5 2022-12-23
6 2022-12-24
7 2022-12-25

In [73]:
date2 = pd.date_range('today' , periods = 3)
date2

DatetimeIndex(['2022-12-18 18:16:45.590137', '2022-12-19 18:16:45.590137',
               '2022-12-20 18:16:45.590137'],
              dtype='datetime64[ns]', freq='D')

In [66]:
date3 = pd.date_range(start = '12/12/2022' , periods =10)
date3

DatetimeIndex(['2022-12-12', '2022-12-13', '2022-12-14', '2022-12-15',
               '2022-12-16', '2022-12-17', '2022-12-18', '2022-12-19',
               '2022-12-20', '2022-12-21'],
              dtype='datetime64[ns]', freq='D')

In [67]:
Rand = np.random.random((10,10))
Rand

array([[0.06135647, 0.52250762, 0.58763089, 0.45802898, 0.24462344,
        0.17548037, 0.05031716, 0.96089966, 0.84174249, 0.51871701],
       [0.99330933, 0.43023614, 0.73876715, 0.36150673, 0.96833452,
        0.76748683, 0.05769228, 0.48083147, 0.20177314, 0.93052051],
       [0.80108134, 0.20723197, 0.54157256, 0.59066884, 0.02252066,
        0.12579994, 0.50163936, 0.35382189, 0.46983164, 0.43857511],
       [0.55309793, 0.05377435, 0.50768804, 0.25034098, 0.9002054 ,
        0.50941647, 0.03096423, 0.72968119, 0.91616283, 0.13783568],
       [0.76253118, 0.09632849, 0.727845  , 0.65876106, 0.02497737,
        0.26842947, 0.71893857, 0.09652777, 0.7796179 , 0.32627726],
       [0.47488706, 0.69680647, 0.16034686, 0.82249602, 0.49089932,
        0.0133429 , 0.87361297, 0.05773117, 0.66030903, 0.0026954 ],
       [0.89842035, 0.15168852, 0.41832784, 0.90957647, 0.63505179,
        0.25222488, 0.50548049, 0.40261347, 0.72230336, 0.23916734],
       [0.1158926 , 0.67312551, 0.7851866

In [68]:
data = pd.DataFrame(Rand , index = date3)
data

0         1         2         3         4         5  \
2022-12-12  0.061356  0.522508  0.587631  0.458029  0.244623  0.175480   
2022-12-13  0.993309  0.430236  0.738767  0.361507  0.968335  0.767487   
2022-12-14  0.801081  0.207232  0.541573  0.590669  0.022521  0.125800   
2022-12-15  0.553098  0.053774  0.507688  0.250341  0.900205  0.509416   
2022-12-16  0.762531  0.096328  0.727845  0.658761  0.024977  0.268429   
2022-12-17  0.474887  0.696806  0.160347  0.822496  0.490899  0.013343   
2022-12-18  0.898420  0.151689  0.418328  0.909576  0.635052  0.252225   
2022-12-19  0.115893  0.673126  0.785187  0.868200  0.905110  0.006692   
2022-12-20  0.980830  0.049600  0.860497  0.049883  0.368688  0.773357   
2022-12-21  0.583095  0.152309  0.156862  0.588891  0.614030  0.406941   

                   6         7         8         9  
2022-12-12  0.050317  0.960900  0.841742  0.518717  
2022-12-13  0.057692  0.480831  0.201773  0.930521  
2022-12-14  0.501639  0.353822  0.469832  0.438575  
2022-12-15  0.030964  0.729681  0.916163  0.137836  
2022-12-16  0.718939  0.096528  0.779618  0.326277  
2022-12-17  0.873613  0.057731  0.660309  0.002695  
2022-12-18  0.505480  0.402613  0.722303  0.239167  
2022-12-19  0.976443  0.525759  0.401771  0.518913  
2022-12-20  0.423682  0.669953  0.785586  0.730465  
2022-12-21  0.699412  0.307175  0.001757  0.201257

In [69]:
# Changing the Column names

In [70]:
data.columns = ['C1','C2','C3','C4','C5','C6','C7','C8','C9','C10']

In [71]:
data

C1        C2        C3        C4        C5        C6  \
2022-12-12  0.061356  0.522508  0.587631  0.458029  0.244623  0.175480   
2022-12-13  0.993309  0.430236  0.738767  0.361507  0.968335  0.767487   
2022-12-14  0.801081  0.207232  0.541573  0.590669  0.022521  0.125800   
2022-12-15  0.553098  0.053774  0.507688  0.250341  0.900205  0.509416   
2022-12-16  0.762531  0.096328  0.727845  0.658761  0.024977  0.268429   
2022-12-17  0.474887  0.696806  0.160347  0.822496  0.490899  0.013343   
2022-12-18  0.898420  0.151689  0.418328  0.909576  0.635052  0.252225   
2022-12-19  0.115893  0.673126  0.785187  0.868200  0.905110  0.006692   
2022-12-20  0.980830  0.049600  0.860497  0.049883  0.368688  0.773357   
2022-12-21  0.583095  0.152309  0.156862  0.588891  0.614030  0.406941   

                  C7        C8        C9       C10  
2022-12-12  0.050317  0.960900  0.841742  0.518717  
2022-12-13  0.057692  0.480831  0.201773  0.930521  
2022-12-14  0.501639  0.353822  0.469832  0.438575  
2022-12-15  0.030964  0.729681  0.916163  0.137836  
2022-12-16  0.718939  0.096528  0.779618  0.326277  
2022-12-17  0.873613  0.057731  0.660309  0.002695  
2022-12-18  0.505480  0.402613  0.722303  0.239167  
2022-12-19  0.976443  0.525759  0.401771  0.518913  
2022-12-20  0.423682  0.669953  0.785586  0.730465  
2022-12-21  0.699412  0.307175  0.001757  0.201257

In [75]:
random = np.random.random((3,3))
print(random)
print(date2)
x = pd.DataFrame(random , index = date2)
x

[[0.70130817 0.89199789 0.36420996]
 [0.84929466 0.49465466 0.80845802]
 [0.42758263 0.03757548 0.25006775]]
DatetimeIndex(['2022-12-18 18:16:45.590137', '2022-12-19 18:16:45.590137',
               '2022-12-20 18:16:45.590137'],
              dtype='datetime64[ns]', freq='D')


0         1         2
2022-12-18 18:16:45.590137  0.701308  0.891998  0.364210
2022-12-19 18:16:45.590137  0.849295  0.494655  0.808458
2022-12-20 18:16:45.590137  0.427583  0.037575  0.250068

In [78]:
x.columns = ['CP9','CP10','CP11']
x

CP9      CP10      CP11
2022-12-18 18:16:45.590137  0.701308  0.891998  0.364210
2022-12-19 18:16:45.590137  0.849295  0.494655  0.808458
2022-12-20 18:16:45.590137  0.427583  0.037575  0.250068

In [82]:
x['CP9'].unique()

array([0.70130817, 0.84929466, 0.42758263])

In [93]:
print(x.dtypes)
print(x.size)
print(x.shape)
print(x.describe())
x['CP10'].nunique()

CP9     float64
CP10    float64
CP11    float64
dtype: object
9
(3, 3)
            CP9      CP10      CP11
count  3.000000  3.000000  3.000000
mean   0.659395  0.474743  0.474245
std    0.213957  0.427559  0.295010
min    0.427583  0.037575  0.250068
25%    0.564445  0.266115  0.307139
50%    0.701308  0.494655  0.364210
75%    0.775301  0.693326  0.586334
max    0.849295  0.891998  0.808458


3

In [90]:
x['CP9'].unique()

array([0.70130817, 0.84929466, 0.42758263])

In [91]:
x['CP9'].nunique()

3

In [99]:
data.sort_values(by = 'C1' , ascending = True)

C1        C2        C3        C4        C5        C6  \
2022-12-12  0.061356  0.522508  0.587631  0.458029  0.244623  0.175480   
2022-12-19  0.115893  0.673126  0.785187  0.868200  0.905110  0.006692   
2022-12-17  0.474887  0.696806  0.160347  0.822496  0.490899  0.013343   
2022-12-15  0.553098  0.053774  0.507688  0.250341  0.900205  0.509416   
2022-12-21  0.583095  0.152309  0.156862  0.588891  0.614030  0.406941   
2022-12-16  0.762531  0.096328  0.727845  0.658761  0.024977  0.268429   
2022-12-14  0.801081  0.207232  0.541573  0.590669  0.022521  0.125800   
2022-12-18  0.898420  0.151689  0.418328  0.909576  0.635052  0.252225   
2022-12-20  0.980830  0.049600  0.860497  0.049883  0.368688  0.773357   
2022-12-13  0.993309  0.430236  0.738767  0.361507  0.968335  0.767487   

                  C7        C8        C9       C10  
2022-12-12  0.050317  0.960900  0.841742  0.518717  
2022-12-19  0.976443  0.525759  0.401771  0.518913  
2022-12-17  0.873613  0.057731  0.660309  0.002695  
2022-12-15  0.030964  0.729681  0.916163  0.137836  
2022-12-21  0.699412  0.307175  0.001757  0.201257  
2022-12-16  0.718939  0.096528  0.779618  0.326277  
2022-12-14  0.501639  0.353822  0.469832  0.438575  
2022-12-18  0.505480  0.402613  0.722303  0.239167  
2022-12-20  0.423682  0.669953  0.785586  0.730465  
2022-12-13  0.057692  0.480831  0.201773  0.930521

In [103]:
data.drop(columns = ['C1'] , inplace = False)

C2        C3        C4        C5        C6        C7  \
2022-12-12  0.522508  0.587631  0.458029  0.244623  0.175480  0.050317   
2022-12-13  0.430236  0.738767  0.361507  0.968335  0.767487  0.057692   
2022-12-14  0.207232  0.541573  0.590669  0.022521  0.125800  0.501639   
2022-12-15  0.053774  0.507688  0.250341  0.900205  0.509416  0.030964   
2022-12-16  0.096328  0.727845  0.658761  0.024977  0.268429  0.718939   
2022-12-17  0.696806  0.160347  0.822496  0.490899  0.013343  0.873613   
2022-12-18  0.151689  0.418328  0.909576  0.635052  0.252225  0.505480   
2022-12-19  0.673126  0.785187  0.868200  0.905110  0.006692  0.976443   
2022-12-20  0.049600  0.860497  0.049883  0.368688  0.773357  0.423682   
2022-12-21  0.152309  0.156862  0.588891  0.614030  0.406941  0.699412   

                  C8        C9       C10  
2022-12-12  0.960900  0.841742  0.518717  
2022-12-13  0.480831  0.201773  0.930521  
2022-12-14  0.353822  0.469832  0.438575  
2022-12-15  0.729681  0.916163  0.137836  
2022-12-16  0.096528  0.779618  0.326277  
2022-12-17  0.057731  0.660309  0.002695  
2022-12-18  0.402613  0.722303  0.239167  
2022-12-19  0.525759  0.401771  0.518913  
2022-12-20  0.669953  0.785586  0.730465  
2022-12-21  0.307175  0.001757  0.201257

In [106]:
# delete using pop
data.pop('C1')

2022-12-12    0.061356
2022-12-13    0.993309
2022-12-14    0.801081
2022-12-15    0.553098
2022-12-16    0.762531
2022-12-17    0.474887
2022-12-18    0.898420
2022-12-19    0.115893
2022-12-20    0.980830
2022-12-21    0.583095
Freq: D, Name: C1, dtype: float64